spring:
  application:
    name: test bank
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/account?createDatabaseIfNotExist=true
    driverClassName: org.postgresql.Driver
    username: account
    password: account
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855